### PR TITLE
Added FeedBack page UI

### PR DESCRIPTION
**Pull request by AkhileshManda**
Feedback page UI added

UI pic : https://drive.google.com/file/d/1eRLMj68x5hLVM8wfIYCrBOv0IH2N61Mf/view?usp=sharing

### CODE REVIEW

**Comment by mrcchef** [comment]
@AkhileshManda 
I have reviewed your code and I have 3 queries:
1) In the RatingBar.Builder(), the updated rating is not printing on the console.
2) In the horizontal view, there is a huge gap b/w the last rating bar and the review text field.
3) The code is not properly formatted. For reference, you may look to other UI screens code.

Please verify above mentioned points and get back to us with your inputs.

**Comment by mrcchef** [comment]
@AkhileshManda 

I more thing, In the HomePage you have removed the existing body and added the feedback screen UI for the development but, when you are creating a pull request, please make sure to make things back to normal and please add the feedback screen to the appropriate position in the app drawer (Menu Widget).

**Comment by AkhileshManda** [comment]
Changes made

- the horizontal issue is fixed (box is smaller), 

- code commented and formatted, 

- Homepage body restored 

- send feedback button( in Menu Widget ) works, 

- Rating bar prints rating on clicking the stars in the console

please review it

**Comment by mrcchef** [comment]
@AkhileshManda 
Thanks for working on suggestions. Things are fine now.
Just one thing to do is when where we are writing in the text field and the text overshoot the width of textfield then the overshooted text should come to the next line. 

After fixing it please verify it in both horizontal and portrait view!!

**Comment by mrcchef** [comment]
@AkhileshManda 
I reviewed that it's completely fine. I am merging your pull request :))

**Pull request merged**
