### PR TITLE
Updated Event List page and drawer

### PR DESCRIPTION
**Pull request by AkhileshManda**
**Features added in drawer:**

- Slider for dark and light mode (only UI)

- Three buttons one for events,one for past events,one for feedback (Navigation needs to be implemented after page design)

- One logout button

**Features added in Event List page:**

- List view of containers each containing event cards and event page is scrollable

- On tapping the card it takes you to the event details page (previously implemented by floating action button on the homepage

- Removed floating action button from home page

Comments added for better readability

**MenuWidget file covers drawer code and EventCard page covers template for event cards**

**Event_List page contains list of events**

**ScreenShots of updated UI:** https://drive.google.com/file/d/12sDaheLFBDs2yBN8H-HcS3M2z0syFp_u/view?usp=sharing

Hope this will be considered for hacktoberfest and contribute-a-thon, please contact me if there is any issue

### CODE REVIEW

**Comment by vikiwarrior** [comment]
@AkhileshManda  Pull from the master branch, resolve conflicts and commit again.

**Comment by AkhileshManda** [comment]
@vikiwarrior resolved sir i added more commits

**Comment by vikiwarrior** [comment]
Capture
Capture1
Fix these and the logout button position. The rest LGTM. Nice Work :+1: @AkhileshManda

**Comment by AkhileshManda** [comment]
Made few changes and it looks fine in my emulator, please check @vikiwarrior sir

**Comment by vikiwarrior** [comment]
Merging this pr and closing this issue. This implementation does not have Listview builder and we might need to use them when we use firebase to fetch event data. Will open up an issue when connecting the event page to firebase. This will probably do for now.:+1:

**Review by vikiwarrior — APPROVED** [review]

**Pull request merged**
